spring:
  profiles:
    include: jwt, oauth
    active: dev
    group:
      dev: common, dev
---
server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: common

  jackson:
    visibility:
      creator: none
      field: any
      getter: none
      is-getter: none
      setter: none

  jpa:
    # ddl 실행 순서 변경
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        # 지연 로딩 최적화(in절)
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        max-page-size: 200
        default-page-size: 10
      sort:
        sort-parameter: "createdAt_desc"
---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: test
      password: test
      connection-init-sql: SELECT 1

  redis:
    port: 6379
    host: localhost
    password: test

logging:
  level:
    org:
      hibernate:
        type: trace
        sql: debug
    root: debug
