spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            scope:
              - profile
              - email

springdoc:
  override-with-generic-response: false
  default-produces-media-type: application/json
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      hibernate:
        type: trace
        sql: debug
    root: debug

token:
  key: test-test-test-test-test
  exp:
    access: 7200000
    refresh: 172800000

oas:
  contact:
    name: test
    email: test
    url: test
