spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

  datasource:
    url:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username:
      password:
      connection-init-sql: SELECT 1

  redis:
    port:
    host:
    password:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - profile
              - email

springdoc:
  override-with-generic-response: false
  default-produces-media-type: application/json
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      hibernate:
        type: trace
        sql: debug
    root: debug

token:
  key:
  exp:
    access:
    refresh:

oas:
  contact:
    name:
    email:
    url:
