spring:
  profiles:
    active: local
    group:
      dev: common, dev
      real: common, real
---
server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: common

  web:
    resources:
      chain:
        enabled: false

  jackson:
    visibility:
      creator: none
      field: any
      getter: none
      is-getter: none
      setter: none

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        max-page-size: 200
        default-page-size: 10
      sort:
        sort-parameter: "createdAt_desc"
