spring:
  profiles:
    include: jwt, oauth
    active: dev
    group:
      dev: common, dev
      real: common, real
---
server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: common

  web:
    resources:
      chain:
        enabled: false

  jackson:
    visibility:
      creator: none
      field: any
      getter: none
      is-getter: none
      setter: none

  jpa:
    # ddl 실행 순서 변경
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        # 지연 로딩 최적화(in절)
        default_batch_fetch_size: 1000

  data:
    web:
      pageable:
        max-page-size: 200
        default-page-size: 10
      sort:
        sort-parameter: "createdAt_desc"
---
logging:
  level:
    org:
      hibernate:
        type: trace
        sql: debug
    root: debug

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: test
      password: test
      connection-init-sql: SELECT 1

  redis:
    port: 6379
    host: localhost
    password: test

springdoc:
  # @ControllerAdvice 응답 추가
  override-with-generic-response: false
  default-produces-media-type: application/json
  cache:
    disabled: true
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /api-docs
    version:
---
spring:
  config:
    activate:
      on-profile: real

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect

  datasource:
    url: jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      connection-init-sql: SELECT 1

  redis:
    port: ${TOKEN_REDIS_PORT}
    host: ${TOKEN_REDIS_HOST}
    password: ${TOKEN_REIDS_PASSWORD}

springdoc:
  swagger-ui:
    enabled: false
